### ISSUE TITLE
wmusic: memory leaks

### ISSUE THREAD

**Issue by wael444** [window-maker/dockapps#42]
i notice that over time, wmusic eats more and more of my memory, one time it took ALL of my available memory.

**Comment by d-torrance** [comment]
I've actually been working on wmusic, including fixing this very bug, recently. Look for a new version soon!

**Comment by wael444** [comment]
yaya

**Comment by d-torrance** [comment]
Fixed in wmusic 2.1.0, which is now available: https://www.dockapps.net/download/wmusic-2.1.0.tar.gz

**Comment by wael444** [comment]
why is it not pushed in this repository?

**Comment by d-torrance** [comment]
It will be soon. The `master` branch here is a just mirror of the main repository at https://repo.or.cz/dockapps. I've submitted the corresponding patches to the Window Maker mailing list, and once they've been applied to the main repository, it will be mirrored here as well.

**Comment by d-torrance** [comment]
It's pushed now!

**Comment by d-torrance** [comment]
Most dockapps are listed on [dockapps.net](https://www.dockapps.net/).  Not all of them are maintained by the Window Maker Team, but a good chunk of them are.  The ones that are maintained by the Window Maker Team are hosted in the git repository I linked above (https://repo.or.cz/wmaker-crm.git), and are then mirrored here at GitHub.  Patches are accepted on the mailing list (wmaker-dev@googlegroups.com).

This GitHub repository exists for this issue tracker and to host dockapps.net.
